# spring=======================================================
server:
  port: 8888

# redis=======================================================
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 1

  # datasource=======================================================
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.139.119.145:3306/v_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: dev
    password: asdfghjkl
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
      auto-commit: true

  mail:
    host: smtp.163.com
    port: 25
    username: csveni@163.com
    password: QTGGPSJDUCBROTTM
    default-encoding: UTF-8

# mybatis=======================================================
mybatis:
  configuration:
    map-underscore-to-camel-case: true
